apiVersion: v1
kind: ConfigMap
metadata:
  name: linkding-container-env
  namespace: linkding-prod
  labels:
    app: linkding
    env: production
data:
  LD_DB_DATABASE: app
  LD_DB_ENGINE: postgres
  LD_DB_HOST: linkding-db-production-cnpg-v1-rw.linkding-prod.svc.cluster.local
  LD_DB_PORT: '5432'
  LD_DB_USER: app
  LD_SUPERUSER_NAME: george
