apiVersion: v1
kind: ConfigMap
metadata:
  name: linkding-oidc-config
  namespace: linkding-prod
  labels:
    app: linkding
    env: production
data:
  LD_ENABLE_OIDC: "True"
  OIDC_RP_CLIENT_ID: "linkding"
  OIDC_OP_AUTHORIZATION_ENDPOINT: "https://auth.burntbytes.com/api/oidc/authorization"
  OIDC_OP_TOKEN_ENDPOINT: "https://auth.burntbytes.com/api/oidc/token"
  OIDC_OP_USER_ENDPOINT: "https://auth.burntbytes.com/api/oidc/userinfo"
  OIDC_OP_JWKS_ENDPOINT: "https://auth.burntbytes.com/jwks.json"
  OIDC_RP_SIGN_ALGO: "RS256"
  OIDC_RP_SCOPES: "openid email profile"
  OIDC_VERIFY_SSL: "True"
