apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - configmap.yaml
  - database.yaml
  - httproute.yaml
  - secret-aws-creds.yaml
  - secret-linkding-container-env.yaml
