# Excalidraw Storage Backend for collaboration scene persistence
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw-storage
  namespace: excalidraw
  labels:
    app: excalidraw-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw-storage
  template:
    metadata:
      labels:
        app: excalidraw-storage
    spec:
      containers:
        - name: excalidraw-storage
          image: alswl/excalidraw-storage-backend:v2023.11.11
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-storage
  namespace: excalidraw
  labels:
    app: excalidraw-storage
spec:
  selector:
    app: excalidraw-storage
  ports:
    - port: 80
      targetPort: 8081
      name: http
