apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich-prod
resources:
  - ../../base/immich/
  - httproute.yaml
  - database.yaml
  - nfs-photos.yaml
  - secret-db-credentials.yaml
  - secret-aws-creds.yaml

labels:
  - pairs:
      env: production
      app.kubernetes.io/instance: production
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
  - path: storage.yaml
  - target:
      kind: Namespace
      name: immich
    patch: |
      - op: replace
        path: /metadata/name
        value: immich-prod
