apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: navidrome-prod
resources:
  - ../../base/navidrome/
  - httproute.yaml
  - nfs-music.yaml

labels:
  - pairs:
      env: production
      app.kubernetes.io/instance: production
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: navidrome
    patch: |
      - op: replace
        path: /metadata/name
        value: navidrome-prod
