apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-config
  namespace: zigbee2mqtt
data:
  configuration.yaml: |
    homeassistant: true
    permit_join: true
    mqtt:
      base_topic: zigbee2mqtt
      server: mqtt://mosquitto.mosquitto-stage
    serial:
      port: /dev/ttyUSB0
    frontend:
      port: 8080
    advanced:
      network_key: GENERATE
