apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  settings.yaml: |
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm
      opacity: 50
    cardBlur: md
    theme: dark
    color: slate

  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/gjcourt/homelab

    - Reference:
        - Kubernetes Docs:
            - abbr: K8s
              href: https://kubernetes.io/docs/
        - Cilium Docs:
            - abbr: CIL
              href: https://docs.cilium.io/

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          storage: true
          showLabel: true
          label: "melodic-muse"
        nodes:
          show: true
          cpu: true
          memory: true
          storage: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank

