apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  settings.yaml: |
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm
      opacity: 50
    cardBlur: md
    theme: dark
    color: slate

  services.yaml: |
    - Applications:
        - Memos:
            icon: memos.png
            href: https://memos-stage.burntbytes.com
            description: Lightweight note-taking service
        - Linkding:
            icon: linkding.png
            href: https://links-stage.burntbytes.com
            description: Bookmark manager
        - Excalidraw:
            icon: excalidraw.png
            href: https://excalidraw-stage.burntbytes.com
            description: Virtual whiteboard for sketching
        - Audiobookshelf:
            icon: audiobookshelf.png
            href: https://audiobooks-stage.burntbytes.com
            description: Audiobook and podcast server
        - Mealie:
            icon: mealie.png
            href: https://mealie-stage.burntbytes.com
            description: Recipe management
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin-stage.burntbytes.com
            description: Media streaming server
        - Immich:
            icon: immich.png
            href: https://photos-stage.burntbytes.com
            description: Photo and video management

    - Infrastructure:
        - Home Assistant:
            icon: home-assistant.png
            href: https://hass-stage.burntbytes.com
            description: Home automation platform
        - AdGuard Home:
            icon: adguard-home.png
            href: https://adguard-stage.burntbytes.com
            description: DNS ad blocker
        - Synology NAS:
            icon: synology-dsm.png
            href: https://192.168.5.8:5001
            description: Network storage
            widget:
              type: diskstation
              url: https://192.168.5.8:5001
              username: {{HOMEPAGE_VAR_SYNOLOGY_USER}}
              password: {{HOMEPAGE_VAR_SYNOLOGY_PASS}}

  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/

    - Reference:
        - Kubernetes Docs:
            - abbr: K8s
              href: https://kubernetes.io/docs/
        - Cilium Docs:
            - abbr: CIL
              href: https://docs.cilium.io/

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "staging"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
