apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage-stage
resources:
  - ../../base/homepage/
  - httproute.yaml
  - secret-synology.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
  - path: configmap.yaml
  - target:
      kind: Namespace
      name: homepage
    patch: |
      - op: replace
        path: /metadata/name
        value: homepage-stage
  - target:
      kind: ClusterRole
      name: homepage
    patch: |
      - op: replace
        path: /metadata/name
        value: homepage-stage
  - target:
      kind: ClusterRoleBinding
      name: homepage
    patch: |
      - op: replace
        path: /metadata/name
        value: homepage-stage
      - op: replace
        path: /roleRef/name
        value: homepage-stage


