apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage-stage
resources:
  - ../../base/homepage/
  - httproute.yaml
  - secret-synology.yaml
  - rbac.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - target:
      kind: Namespace
      name: homepage
    patch: |
      - op: replace
        path: /metadata/name
        value: homepage-stage

configMapGenerator:
  - name: homepage
    namespace: homepage
    behavior: merge
    files:
      - services.yaml


