# Patch to add collaboration config for self-hosted excalidraw
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
  namespace: excalidraw
spec:
  template:
    spec:
      containers:
        - name: excalidraw
          env:
            - name: VITE_APP_WS_SERVER_URL
              value: "wss://excalidraw-room-stage.burntbytes.com"
            - name: VITE_APP_STORAGE_BACKEND
              value: "http"
            - name: VITE_APP_HTTP_STORAGE_BACKEND_URL
              value: "https://excalidraw-storage-stage.burntbytes.com/api/v2"
            - name: VITE_APP_FIREBASE_CONFIG
              value: "{}"
            - name: VITE_APP_DISABLE_TRACKING
              value: "true"
