apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: excalidraw-stage
resources:
  - ../../base/excalidraw/
  - httproute.yaml
  - room-httproute.yaml
  - storage-httproute.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
  - target:
      kind: Namespace
      name: excalidraw
    patch: |
      - op: replace
        path: /metadata/name
        value: excalidraw-stage
