apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mosquitto-stage
resources:
  - ../../base/mosquitto

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: mosquitto
    patch: |
      - op: replace
        path: /metadata/name
        value: mosquitto-stage
