apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-container-env
  namespace: adguard-stage
  labels:
    app: adguard
    env: staging
data:
  ADGUARD_HTTP_PORT: '80'
  ADGUARD_HTTPS_PORT: '443'
  ADGUARD_LISTEN_ADDR: 0.0.0.0
