apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adguard
resources:
  - ../../base/adguard
  - configmap.yaml
  - httproute.yaml
  - secret-adguard-container-env.yaml
  - storage.yaml

patches:
  - path: deployment-patch.yaml
