apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adguard-stage
resources:
  - ../../base/adguard
  - configmap.yaml
  - httproute.yaml
  - secret-adguard-container-env.yaml
  - storage.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
  - target:
      kind: Namespace
      name: adguard
    patch: |
      - op: replace
        path: /metadata/name
        value: adguard-stage
