apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adguard-stage
resources:
  - ../../base/adguard
  - configmap.yaml
  - httproute.yaml
  - secret-adguard-container-env.yaml
  - secret-sync.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - target:
      kind: Service
      name: adguard
    patch: |
      - op: replace
        path: /metadata/annotations/lbipam.cilium.io~1sharing-cross-namespace
        value: default,adguard-stage,audiobookshelf-stage,linkding-stage,mealie-stage,memos-stage
  - target:
      kind: Namespace
      name: adguard
    patch: |
      - op: replace
        path: /metadata/name
        value: adguard-stage
  - target:
      kind: StatefulSet
      name: adguard
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: adguard
      spec:
        replicas: 2
