apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adguard
resources:
  - ../../base/adguard
  - configmap.yaml
  - database.yaml
  - secret-adguard-container-env.yaml
  - httproute.yaml

patchesStrategicMerge:
  - patch-deployment-cnpg.yaml
