apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config-file
  namespace: immich-stage
data:
  immich-config.json: |
    {
      "ffmpeg": {
        "accel": "vaapi"
      },
      "oauth": {
        "enabled": true,
        "issuerUrl": "https://auth.stage.burntbytes.com",
        "clientId": "immich",
        "clientSecret": "__CLIENT_SECRET_PLACEHOLDER__",
        "scope": "openid email profile",
        "buttonText": "Login with Authelia",
        "autoRegister": true,
        "autoLaunch": false
      }
    }
