apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich-stage
resources:
  - ../../base/immich/
  - config-file.yaml
  - database.yaml
  - httproute.yaml
  - nfs-photos.yaml
  - secret-aws-creds.yaml
  - secret-db-credentials.yaml
  - secret-sso.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
  - path: storage.yaml
  - path: job-patch.yaml
  - target:
      kind: Namespace
      name: immich
    patch: |
      - op: replace
        path: /metadata/name
        value: immich-stage
