apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: home-compute-pool
spec:
  blocks:
    - start: 192.168.5.30
      stop: 192.168.5.255
    # - start: 10.42.2.30
    #   stop: 10.42.2.255