apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant-prod
resources:
  - ../../base/homeassistant/
  - httproute.yaml

labels:
  - pairs:
      env: production
      app.kubernetes.io/instance: production
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: homeassistant
    patch: |
      - op: replace
        path: /metadata/name
        value: homeassistant-prod
