apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom-zone
  namespace: dns-system
data:
  stage.burntbytes.com: |
    $ORIGIN stage.burntbytes.com.
    @ 3600 IN SOA sns.dns.icann.org. noc.dns.icann.org. (
            2017042745 ; serial
            7200       ; refresh (2 hours)
            3600       ; retry (1 hour)
            1209600    ; expire (2 weeks)
            3600       ; minimum (1 hour)
            )
