apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf-stage
resources:
  - ../../base/audiobookshelf/
  - httproute.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: audiobookshelf
    patch: |
      - op: replace
        path: /metadata/name
        value: audiobookshelf-stage