apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cilium
  - cnpg
  - coredns-internal
  - kube-prometheus-stack
  - loki
  - mosquitto
  - promtail
  - renovate
  - snapshot
  - synology-csi
  - zigbee2mqtt