apiVersion: v1
kind: Secret
metadata:
    name: traefik-web-password
    namespace: traefik
data:
    password: ENC[AES256_GCM,data:Ocsq1zM5wG4/lgUVgPaeLqjyY7usQUuNDtF+5XxT9Hw=,iv:wS64KrgcnNB9r5M9Uso1A1OYAT0ob4EBw2AICwUce6A=,tag:xJc+mOYFwKCZ1BOIXSqdXw==,type:str]
sops:
    age:
        - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidHZXUlBlQVlSWmtBbnBO
            NXIzYU03QkRLYU1BNnBZb09KdVV4bXdJWmlVCmNmTkQyVzNuYXRiYjZUVzhXUkRT
            RGhRWW1Gb1RLZHhRWW51a2Rsblp1c28KLS0tIHNrV2ltQ1NpR2xWNnU4NHR4RFlj
            aitlNXdDbkVhWnM0aUJ6eHZOSGhoL1EK7xAQ7lje5iwU6n5TB6HgSsIU/uj05XaV
            JztRFtpzkavZKkqL8IhM8PcYQtq4S2rwm3LzC81U4PbFLJ+bFhyp9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T22:56:23Z"
    mac: ENC[AES256_GCM,data:Yu157xH5B1Fkvtwq0wQ2S+tVq9HOpIaT8HvFqhZojGpDVr77IHpPOHyG7uC/7Q0in4e2iXJezvKAKjJRtXzMofg7ZuXJgNukolr7QCkgFbgznk6M7rAbFEXpkh2ZMgaGKKxN4en9yAwVYAIABg/Yqe3hJYyQoAVKsD5GgBwzfXE=,iv:RQDkvMTRuERNkV3rmlithDySZdKsaJqajvbkm2PU1v0=,tag:WCJjv6+aQkDWtAM+LE+2mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2

