apiVersion: v1
kind: Service
metadata:
  name: vitals
  namespace: vitals
  labels:
    app: vitals
spec:
  type: ClusterIP
  selector:
    app: vitals
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
