apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: snapcast-prod
resources:
  - ../../base/snapcast/
  - httproute.yaml

labels:
  - pairs:
      env: production
      app.kubernetes.io/instance: production
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: snapcast
    patch: |
      - op: replace
        path: /metadata/name
        value: snapcast-prod
