apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zigbee2mqtt-stage
resources:
  - ../../base/zigbee2mqtt
  - httproute.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: zigbee2mqtt
    patch: |
      - op: replace
        path: /metadata/name
        value: zigbee2mqtt-stage
