apiVersion: v1
kind: ConfigMap
metadata:
  name: vitals-container-env
  namespace: vitals-stage
  labels:
    app: vitals
    env: staging
data:
  ADDR: ":8080"
  DB_HOST: vitals-db-staging-cnpg-v1-rw.vitals-stage.svc.cluster.local
  WEB_DIR: "/web"
