apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vitals-stage
resources:
  - ../../base/vitals/
  - configmap.yaml
  - database.yaml
  - httproute.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - secret-aws-creds.yaml
  - secret-db-credentials.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: vitals
    patch: |
      - op: replace
        path: /metadata/name
        value: vitals-stage
