apiVersion: v1
kind: ConfigMap
metadata:
  name: biometrics-container-env
  namespace: biometrics-stage
  labels:
    app: biometrics
    env: staging
data:
  ADDR: ":8080"
  DB_HOST: biometrics-db-staging-cnpg-v1-rw.biometrics-stage.svc.cluster.local
  WEB_DIR: "/web"
