apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-dns
  namespace: adguard
  labels:
    app.kubernetes.io/name: adguard-dns
    app.kubernetes.io/component: dns
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard-dns
      app.kubernetes.io/component: dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adguard-dns
        app.kubernetes.io/component: dns
    spec:
      containers:
        - name: adguard
          image: adguard/adguardhome:latest

          envFrom:
            - configMapRef:
                name: adguard-container-env
            - secretRef:
                name: adguard-container-env-secret

          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP

      restartPolicy: Always
