apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-web.yaml
  - deployment-dns.yaml
  - httproute.yaml
  - namespace.yaml
  - service-web.yaml
  - service-dns.yaml
  - storage.yaml
