apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: adguard
  labels:
    app: adguard
    app.kubernetes.io/name: adguard
  annotations:
    lbipam.cilium.io/ip-pool: single-node-pool
    lbipam.cilium.io/sharing-cross-namespace: default,audiobookshelf,linkding,mealie,pihole,adguard
    lbipam.cilium.io/sharing-key: homelab
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: adguard
  ports:
    - name: setup
      port: 3000
      targetPort: 3000
    - name: http
      port: 8080
      targetPort: http
    - name: https
      port: 8443
      targetPort: https
    - name: dns
      port: 53
      targetPort: dns
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
