apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      # App runs as node user, limits the scope of pods to the same user.
      securityContext:
        runAsUser: 1000 # node user ID
        runAsGroup: 1000 # node group ID
        fsGroup: 1000 # node group ID

      containers:
        - image: ghcr.io/advplyr/audiobookshelf:latest
          name: audiobookshelf
          ports:
            - containerPort: 13378
          envFrom:
            - configMapRef:
                name: audiobookshelf-container-env
          volumeMounts:
            - name: audiobookshelf-data
              mountPath: /usr/share/audiobookshelf/config
      volumes:
        - name: audiobookshelf-data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-pvc


