apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
  annotations:
    # metallb.io/allow-shared-ip: homelab
    lbipam.cilium.io/sharing-key: homelab
  labels:
    app: audiobookshelf
    color: blue
type: LoadBalancer
spec:
  ports:
    - name: http
      port: 3005
      protocol: TCP
      targetPort: 13378
  selector:
    app: audiobookshelf