apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
  annotations:
    # metallb.io/allow-shared-ip: homelab
    "lbipam.cilium.io/sharing-key": homelab
    foo: bar
  labels:
    app: audiobookshelf
    color: blue
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3005
      protocol: TCP
      targetPort: 13378
  selector:
    app: audiobookshelf