apiVersion: v1
kind: Service
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
  namespace: audiobookshelf
  annotations:
    metallb.io/allow-shared-ip: homelab
type: ClusterIP
spec:
  ports:
    - name: http-web
      port: 3000
      protocol: HTTP
      targetPort: 13378
  selector:
    app: audiobookshelf