apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adguard-prod
resources:
  - ../../base/adguard
  - configmap.yaml
  - httproute.yaml
  - secret-adguard-container-env.yaml
  - secret-sync.yaml

labels:
  - pairs:
      env: production
      app.kubernetes.io/instance: production
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: adguard
    patch: |
      - op: replace
        path: /metadata/name
        value: adguard-prod
