apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: navidrome-stage
resources:
  - ../../base/navidrome/
  - httproute.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: navidrome
    patch: |
      - op: replace
        path: /metadata/name
        value: navidrome-stage
