apiVersion: v1
kind: Service
metadata:
  name: biometrics
  namespace: biometrics
  labels:
    app: biometrics
spec:
  type: ClusterIP
  selector:
    app: biometrics
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
