apiVersion: v1
kind: ConfigMap
metadata:
  name: linkding-container-env
  namespace: linkding
  labels:
    app: linkding
    env: staging
# Options from https://linkding.link/options/
data:
  LD_SUPERUSER_NAME: george
  LD_DB_ENGINE: postgres
  LD_DB_HOST: linkding-db-staging-cnpg-v1-rw.linkding.svc.cluster.local
  LD_DB_PORT: '5432'
