apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding-stage
resources:
  - ../../base/linkding/
  # - cloudflare.yaml
  - configmap.yaml
  - configmap-oidc.yaml
  - database.yaml
  - httproute.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - secret-app.yaml
  - secret-aws-creds.yaml
  - secret-cloudflare-tunnel.yaml
  - secret-db-credentials.yaml
  - secret-oidc.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
  - target:
      kind: Namespace
      name: linkding
    patch: |
      - op: replace
        path: /metadata/name
        value: linkding-stage
