apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mosquitto
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    listener 1883
    # Allow anonymous for internal subnet, or user/pass.
    # For simplicity in homelab internal cluster:
    allow_anonymous true
