apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate-wildcard.yaml
  - certificates.yaml
  - clusterissuer.yaml
  - namespace.yaml
  - referencegrant.yaml
  - secret-cloudflare-api-token.yaml
  - secret-tls-creds.yaml