# Helm values

# Storage Classes
storageClasses:
  synology-iscsi: # Persistent storage class
    isDefault: true
    parameters:
      dsm: 192.168.5.8
      location: /volume1
      protocol: iscsi
      fsType: btrfs
    reclaimPolicy: Retain

  synology-iscsi-ephemeral: # Ephemeral storage class
    parameters:
      dsm: 192.168.5.8
      location: /volume1
      protocol: iscsi
      fsType: btrfs
    reclaimPolicy: Delete
    allowVolumeExpansion: true

  synology-nfs: # NFS storage class for shared media
    parameters:
      dsm: 192.168.5.8
      location: /volume1
      protocol: nfs
    reclaimPolicy: Retain
    allowVolumeExpansion: true

# Volume Snapshot Classes
volumeSnapshotClasses:
  synology-iscsi-snapshot:
    deletionPolicy: Delete
    parameters:
      description: Kubernetes CSI
