apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml

configMapGenerator:
  - name: promtail-helm-values
    namespace: monitoring
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml
