apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: security
type: Opaque
stringData:
    #ENC[AES256_GCM,data:bjZejl0ArXGYGOGjGDSTqcp9MESxcbVVGKBr0/s90KcZ2FRjHP5StLLPU13YhMLB8cSmBqjwYy9dq7PY3mxKdKMl5OW+tUDTSqRz,iv:7hi0X9/S9dpj+lOr4+9MicgRWwC9FMsvLo0YT2fEzss=,tag:o/rszBgFRvXOUO3yeVHR9A==,type:comment]
    #ENC[AES256_GCM,data:rqcjXgeD0SlwTrTxDyZXK9BkZZCWhsOfW7q5zXjZyKFGVRVkba2qPYq06zF6Z+ckEJLUTo4VlZEN,iv:OdMSxjX/musVu9GXaizA8TuaBcipftBv3x27cSmihGo=,tag:/iBefc3R1G6wul9b0CbhKg==,type:comment]
    api-token: ENC[AES256_GCM,data:e92bBBDn8dYqWIzCWsGxvVLKBNFUEgHjiZ19fl2DSF0VfqNybaGMtg==,iv:UB7WqlpgjFXfBtS5FftTw5GSKkiE2i5x3q2YJGwHxHk=,tag:gZfMJPnzXnuNg66tlzv1OA==,type:str]
sops:
    age:
        - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bUJDYTVUTUZZa1lIeFA4
            dWhxa3NGR3JHK2NWZTc1ZXdJb3lnb3k1dkV3CjJzTUlvR2UrckpoNm1lNlNKTmls
            TGVwKzJ2NGIzWEwrbFhiajhwSUxsRFUKLS0tIEZXOHpudGFyWkNpeDczZ0ZBTzVq
            KzdraFBjbE56dVVUUjJZWXJERUJEcGcK3TXOW7LU8kTOj2NubJDVm1PPnL3yZlm2
            T15I/BxJIwT699nLWF7+v+8XOS4cLOQ1CpkUHtPE3shqGt1/8g76jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T06:27:30Z"
    mac: ENC[AES256_GCM,data:uugUgpaVUMcuNyFTpBYOKySOWN8HjVgTS8A+njdeq0noG0ZBMDEuSOey8u5xEKmD5ki+yF/iqpCjzYPlGeTn3oRvVtiRdb2YeEe+vuBt1vdJZhTLHiS7UgRTp76+sLmvB6qxX3KISwPmHV+5c+2lxd+DEiy4BA2CyjUwQH08d14=,iv:mM8bKLzjhLd1VoKRbV2uiVqF7R9gGX2osyMpXBncCsE=,tag:kjrxL7Q62ICb09XujaDxfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
