apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: security
type: Opaque
stringData:
  #ENC[AES256_GCM,data:+n7nL9avYk90A6/yMlHMae22hM0mUP6MpHzpViMTYkN3yuv0AIDaEhZBido6jJ0Co2xVUDAZzBG2s84fzCxdAN+uoKbypd9kY/Aj,iv:Ebbt0XKgWh9p5lYaMKOslp4t5US3sBD8icwBMi+ErQk=,tag:ok1ZxyvhZSJal70aBwNjRA==,type:comment]
  #ENC[AES256_GCM,data:nckQbVYLUWnyIgGEC+i1vgcMw9EQphvI3abF//FhhJzjeC9Ghe2sUy0td7a3kR1w5dliU/Dg/T/V,iv:8lKJOlEXWqCJg7Phh6VPNnDKr/+FsXnCHWAxQ/6h7/U=,tag:nJAIs/o62OXCYaTBIAomJg==,type:comment]
  api-token: ENC[AES256_GCM,data:YjJd+VKNqXExDWZpIHNF+DdEy5EsZKzlRVnCQbe8b6OXz2Ks8Urhhw==,iv:S8e6ZRJIntYNd85v/PlMl7xv/WVH9WIOftoHd9Uz6kY=,tag:vMiVNFpQCrNe+BkffRoM+g==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdml5MExDWnd5YUkvTDcv
        elh6NytPYzljaEhpRmN2bnNKZ3F4TzNoWVEwCkJmRHZORlpxdGhrUTcyV3l5Ykx5
        bmdEeWE3TDhET3RFRGJFT1AyT1hudEEKLS0tIFhQWUJKTlNuNmdUR0lPc251aEQ4
        c0V2NERyOHE2cDZJRjhuQUZIOGZ2SG8KgRsmVDntaJCNElqoRpkNE/b2RL6ycRnk
        0Tn+o1iDkQXtsyQ2cMm/KWldFVW7NtQo2dUCeXJQ7OuC7+L9d5UM+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T06:38:11Z"
  mac: ENC[AES256_GCM,data:UMPJpVFyAPf9Ls5719KNAZUzJest61TWpYUUmw4ld0ja8eujzHmRW+n2pQz+OeKHK0CqIc1kcv5bprnzGGktirrQj71JjtSdRv6E4jtOrcUK4TILkPMjRAUDB/9XfjhwLVhl0zAIgDQ6RXn7DBVDLQMR/fgJyRMhPx5FtlRJOoU=,iv:9WHqCza+jUXq0kNj45FmtruLss87SxBP95P8DKf+ZhA=,tag:qgiUbRDP8xvvCQDn7VXQ0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
