apiVersion: v1
kind: Service
metadata:
  name: memos
  namespace: memos
  labels:
    app: memos
spec:
  type: ClusterIP
  selector:
    app: memos
  ports:
    - name: http
      port: 5230
      targetPort: 5230
---
apiVersion: v1
kind: Service
metadata:
  name: memos-grpc
  namespace: memos
  labels:
    app: memos
spec:
  type: ClusterIP
  selector:
    app: memos
  ports:
    - name: grpc
      port: 5230
      targetPort: 5230
      appProtocol: kubernetes.io/h2c
