apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - audiobookshelf
  - authelia
  - vitals
  - certificates
  - cloudflare-tunnel
  - excalidraw
  - golinks
  - homepage
  - homeassistant
  - immich
  - ingress
  - jellyfin
  - linkding
  - mealie
  - memos
  - navidrome
  - snapcast
  - synology-iscsi-monitor
