apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - audiobookshelf
  - authelia
  - certificates
  - cloudflare-tunnel
  - excalidraw
  - homepage
  - homeassistant
  - immich
  - ingress
  - jellyfin
  - linkding
  - mealie
  - memos
  - snapcast
