apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  settings.yaml: |
    title: BurntBytes Home
    description: Production Environment
    headerStyle: clean
    layout:
      Media:
        style: row
        columns: 4
      Tools:
        style: row
        columns: 4
      Infrastructure:
        style: row
        columns: 4
      Monitoring:
        style: row
        columns: 4
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm
      opacity: 50
    cardBlur: md
    theme: dark
    color: slate

  bookmarks.yaml: |
    - Developer:
        - homelab:
            - abbr: HL
              href: https://github.com/gjcourt/homelab
        - brainstorm:
            - abbr: BS
              href: https://github.com/gjcourt/brainstorm

    - Reference:
        - Kubernetes Docs:
            - abbr: K8s
              href: https://kubernetes.io/docs/
        - Cilium Docs:
            - abbr: CIL
              href: https://docs.cilium.io/

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "production"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
