apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage-prod
resources:
  - ../../base/homepage/
  - httproute.yaml
  - rbac.yaml
  - secret-synology.yaml

labels:
  - pairs:
      env: production
      app.kubernetes.io/instance: production
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - target:
      kind: Namespace
      name: homepage
    patch: |
      - op: replace
        path: /metadata/name
        value: homepage-prod

configMapGenerator:
  - name: homepage
    namespace: homepage
    behavior: merge
    files:
      - services.yaml
