apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memos-prod
resources:
  - ../../base/memos/
  - configmap.yaml
  - database.yaml
  - httproute.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - secret-aws-creds.yaml
  - secret-db-credentials.yaml
  - secret-sso.yaml

labels:
  - pairs:
      env: production
      app.kubernetes.io/instance: production
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
  - target:
      kind: Namespace
      name: memos
    patch: |
      - op: replace
        path: /metadata/name
        value: memos-prod
