apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memos
resources:
  - ../../base/memos/
  - configmap.yaml
  - database.yaml
  - httproute.yaml
  - secret-aws-creds.yaml

patches:
  - path: deployment-patch.yaml

nameSuffix: ""
