apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana-http
  namespace: monitoring
spec:
  hostnames:
    - grafana.burntbytes.com
  parentRefs:
    - name: app-gateway-staging
      namespace: default
      sectionName: http-prod
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana-https
  namespace: monitoring
spec:
  hostnames:
    - grafana.burntbytes.com
  parentRefs:
    - name: app-gateway-staging
      namespace: default
      sectionName: https-prod
  rules:
    - backendRefs:
        - name: kube-prometheus-stack-grafana
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana-internal
  namespace: monitoring
spec:
  hostnames:
    - grafana.burntbytes.com
  parentRefs:
    - name: app-gateway-production
      namespace: default
      sectionName: http-internal
  rules:
    - backendRefs:
        - name: kube-prometheus-stack-grafana
          port: 80