apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana-production
  namespace: monitoring
spec:
  hostnames:
    - grafana.burntbytes.com # Match requests
  parentRefs:
    - name: app-gateway-production
      namespace: default
      sectionName: http-internal
  rules:
    - backendRefs:
      - name: kube-prometheus-stack-grafana
        port: 80