apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httproute.yaml
  - namespace.yaml
  - release.yaml
  - repository.yaml
  - secrets.yaml

configMapGenerator:
  - name: kube-prometheus-stack-helm-values
    namespace: monitoring
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml
