apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin-stage
resources:
  - ../../base/jellyfin/
  - httproute.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

# Replace base storage with staging-specific storage
patchesStrategicMerge:
  - storage.yaml

patches:
  - target:
      kind: Namespace
      name: jellyfin
    patch: |
      - op: replace
        path: /metadata/name
        value: jellyfin-stage
  # Rename PVs to avoid conflict with production
  - target:
      kind: PersistentVolume
      name: jellyfin-movies-pv
    patch: |
      - op: replace
        path: /metadata/name
        value: jellyfin-movies-pv-staging
  - target:
      kind: PersistentVolumeClaim
      name: jellyfin-movies-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: jellyfin-movies-pv-staging
  - target:
      kind: PersistentVolume
      name: jellyfin-tvshows-pv
    patch: |
      - op: replace
        path: /metadata/name
        value: jellyfin-tvshows-pv-staging
  - target:
      kind: PersistentVolumeClaim
      name: jellyfin-tvshows-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: jellyfin-tvshows-pv-staging
  - target:
      kind: PersistentVolume
      name: jellyfin-tvanime-pv
    patch: |
      - op: replace
        path: /metadata/name
        value: jellyfin-tvanime-pv-staging
  - target:
      kind: PersistentVolumeClaim
      name: jellyfin-tvanime-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: jellyfin-tvanime-pv-staging
