apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nodeport.yaml
  - release.yaml
  - repository.yaml

configMapGenerator:
  - name: vector-helm-values
    namespace: monitoring
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml
