apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - audiobookshelf
  - certificates
  - excalidraw
  - homepage
  - ingress
  - jellyfin
  - linkding
  - mealie
  - memos