apiVersion: apps/v1
kind: Deployment

metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole

spec:
  replicas: 1

  selector:
    matchLabels:
      app: pihole

  template:
    metadata:
      labels:
        app: pihole

    spec:
      containers:
        - name: pihole
          image: ghcr.io/pi-hole/pihole:2025.08.0
          ports:
            - containerPort: 80
              name: admin-port
              protocol: TCP
            - containerPort: 53
              name: dns-port-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-port-udp
              protocol: UDP

          envFrom:
            - configMapRef:
                name: pihole-container-env

          volumeMounts:
            - name: pihole-data
              mountPath: /etc/pihole
            - name: pihole-webpass-data
              mountPath: /

      volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pihole-data-pvc
        - name: pihole-webpass-data
          secret:
            secretName: pihole-webpass-secret
            # Optional: Define permissions for the mounted files
            defaultMode: 0400
            # Optional: Select specific keys to mount as files
            items:
              - key: pihole_password.txt
                path: ./pihole_password.txt