apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - httproute.yaml
  - namespace.yaml
  - service-dns.yaml # not working
  - service.yaml
  - storage.yaml
  - udproute.yaml # not working