apiVersion: v1
kind: ConfigMap
metadata:
  name: biometrics-container-env
  namespace: biometrics-prod
  labels:
    app: biometrics
    env: production
data:
  ADDR: ":8080"
  DB_HOST: biometrics-db-production-cnpg-v1-rw.biometrics-prod.svc.cluster.local
  WEB_DIR: "/web"
