apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin-prod
resources:
  - ../../base/jellyfin/
  - httproute.yaml

labels:
  - pairs:
      env: production
      app.kubernetes.io/instance: production
    includeSelectors: false

# Replace base storage with production-specific storage
patchesStrategicMerge:
  - storage.yaml

patches:
  - target:
      kind: Namespace
      name: jellyfin
    patch: |
      - op: replace
        path: /metadata/name
        value: jellyfin-prod
  # Rename PVs to avoid conflict with staging
  - target:
      kind: PersistentVolume
      name: jellyfin-movies-pv
    patch: |
      - op: replace
        path: /metadata/name
        value: jellyfin-movies-pv-prod
  - target:
      kind: PersistentVolumeClaim
      name: jellyfin-movies-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: jellyfin-movies-pv-prod
  - target:
      kind: PersistentVolume
      name: jellyfin-tvshows-pv
    patch: |
      - op: replace
        path: /metadata/name
        value: jellyfin-tvshows-pv-prod
  - target:
      kind: PersistentVolumeClaim
      name: jellyfin-tvshows-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: jellyfin-tvshows-pv-prod
  - target:
      kind: PersistentVolume
      name: jellyfin-tvanime-pv
    patch: |
      - op: replace
        path: /metadata/name
        value: jellyfin-tvanime-pv-prod
  - target:
      kind: PersistentVolumeClaim
      name: jellyfin-tvanime-pvc
    patch: |
      - op: replace
        path: /spec/volumeName
        value: jellyfin-tvanime-pv-prod
