apiVersion: v1
kind: ConfigMap
metadata:
  name: vitals-container-env
  namespace: vitals-prod
  labels:
    app: vitals
    env: production
data:
  ADDR: ":8080"
  DB_HOST: vitals-db-production-cnpg-v1-rw.vitals-prod.svc.cluster.local
  WEB_DIR: "/web"
