apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  # WARN Current unsupported by Cilium
  # https://github.com/cilium/cilium/issues/21929
  # - gateway-dns.yaml # not working
  - gateway.yaml
