apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml

configMapGenerator:
  - name: cnpg-helm-values
    namespace: cnpg-system
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
