apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: navidrome
  labels:
    app: navidrome
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4533
      protocol: TCP
      targetPort: 4533
  selector:
    app: navidrome
