apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - audiobookshelf
  - authelia
  - biometrics
  - golinks
  - immich
  - jellyfin
  - linkding
  - mealie
  - memos
  - snapcast
