apiVersion: v1
kind: Service
metadata:
  name: golinks
  namespace: golinks
  labels:
    app: golinks
spec:
  type: ClusterIP
  selector:
    app: golinks
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
