apiVersion: v1
kind: ConfigMap
metadata:
  name: golinks-container-env
  namespace: golinks-prod
  labels:
    app: golinks
    env: production
data:
  DB_HOST: golinks-db-production-cnpg-v1-rw.golinks-prod.svc.cluster.local
  GOLINKS_PORT: "8080"
