apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: golinks-prod
resources:
  - ../../base/golinks/
  - configmap.yaml
  - database.yaml
  - httproute.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - secret-aws-creds.yaml
  - secret-db-credentials.yaml

labels:
  - pairs:
      env: production
      app.kubernetes.io/instance: production
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: golinks
    patch: |
      - op: replace
        path: /metadata/name
        value: golinks-prod
