apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - dashboard.yaml
configMapGenerator:
  - name: authelia-config
    namespace: authelia
    files:
      - configuration.yaml
