apiVersion: v1
kind: Service
type: ClusterIP
metadata:
  name: authelia
  namespace: authelia
  labels:
    app: authelia
spec:
  selector:
    app: authelia
  ports:
    - name: http
      port: 9091
      targetPort: http
    - name: metrics
      port: 9959
      targetPort: metrics
