apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
  labels:
    app: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      # App runs as www-data user, limits the scope of pods to the same user.
      securityContext:
        runAsUser: 33 # www-data user ID
        runAsGroup: 33 # www-data group ID
        fsGroup: 33 # www-data group ID

      containers:
        - name: linkding
          image: sissbruecker/linkding@sha256:61b2eb9eed8e5772a473fb7f1f8923e046cb8cbbeb50e88150afd5ff287d4060
          ports:
            - containerPort: 9090

          env:
            - name: LD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-db-credentials
                  key: password

          envFrom:
            - configMapRef:
                name: linkding-container-env
            - secretRef:
                name: linkding-app-secret

          # Mount required for Huey tasks queues (can be moved to redis, though
          # this is defined in the INSTALLED_APPS)
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data

          securityContext:
            allowPrivilegeEscalation: false

      # TODO upgrade this to a postgres backed DB instead of a PV
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc