apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
  labels:
    app: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      # App runs as www-data user, limits the scope of pods to the same user.
      securityContext:
        runAsUser: 33 # www-data user ID
        runAsGroup: 33 # www-data group ID
        fsGroup: 33 # www-data group ID

      containers:
        - name: linkding
          image: sissbruecker/linkding:1.43.0
          ports:
            - containerPort: 9090

          envFrom:
            - configMapRef:
                name: linkding-container-env
            - secretRef:
                name: linkding-container-env-secret

          # volumeMounts:
          #   - name: linkding-data
          #     mountPath: /etc/linkding/data

          securityContext:
            allowPrivilegeEscalation: false

      # TODO upgrade this to a postgres backed
      # DB instead of a PV
      # volumes:
      #   - name: linkding-data
      #     persistentVolumeClaim:
      #       claimName: linkding-data-pvc