apiVersion: v1
kind: Service
metadata:
  name: linkding
  namespace: linkding
  labels:
    app: linkding
spec:
  type: ClusterIP
  selector:
    app: linkding
  ports:
    - name: http
      port: 9090
      # port: 9001
      # protocol: TCP
      # targetPort: 9090
