apiVersion: v1
kind: Service
metadata:
  name: linkding
  namespace: linkding
  annotations:
    lbipam.cilium.io/sharing-key: homelab
    lbipam.cilium.io/sharing-cross-namespace: default,audiobookshelf,linkding,mealie,pihole
  labels:
    app: linkding
spec:
  type: ClusterIP
  selector:
    app: linkding
  ports:
    - name: http
      port: 9090
      # port: 9001
      # protocol: TCP
      # targetPort: 9090