apiVersion: v1
kind: Service
metadata:
  name: linkding
  namespace: linkding
  annotations:
    # metallb.io/allow-shared-ip: homelab
    # lbipam.cilium.io/sharing-key: homelab
  labels:
    app: linkding
    color: blue
type: ClusterIP
spec:
  ports:
    - name: http
      port: 9090
      # port: 9001
      # protocol: TCP
      # targetPort: 9090
  selector:
    app: linkding