apiVersion: v1
kind: Service
metadata:
  name: linkding
  namespace: linkding
  annotations:
    # lbipam.cilium.io/sharing-key: homelab
    # lbipam.cilium.io/sharing-cross-namespace: audiobookshelf,linkding,mealie
  labels:
    app: linkding
    color: blue
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      # port: 9001
      # protocol: TCP
      # targetPort: 9090
  selector:
    app: linkding