apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
  labels:
    app: immich
data:
  # Immich configuration
  IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
  MACHINE_LEARNING_WORKERS: "1"
  MACHINE_LEARNING_WORKER_TIMEOUT: "300"
  REDIS_HOSTNAME: "immich-redis"
  REDIS_PORT: "6379"
  # Paths
  UPLOAD_LOCATION: "/usr/src/app/upload"
  # Timezone
  TZ: "America/Los_Angeles"
